# Generated by Django 3.1.5 on 2021-02-04 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PCStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressId', models.AutoField(primary_key=True, serialize=False)),
                ('line1', models.CharField(max_length=100)),
                ('line2', models.CharField(max_length=100)),
                ('line3', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('holderName', models.CharField(max_length=200)),
                ('cardNum', models.IntegerField()),
                ('expireMonth', models.IntegerField()),
                ('expireYear', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('addressId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCStore.address')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contactNum', models.IntegerField()),
                ('addressId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCStore.address')),
                ('paymentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCStore.payment')),
            ],
        ),
    ]
